<form class="form-inline">
  <input type="text" class="input-small" placeholder="用户名">
  <input type="text" class="input-medium" placeholder="邮箱">
  <button type="submit" class="btn  btn-primary" id="search">查询</button>
</form>
<table class="table table-hover">
	<thead>
		<tr>
			<th>#</th>
			<th>用户名</th>
			<th>邮箱</th>
			<th>真实姓名</th>
			<th>邮箱</th>
			<th>真实姓名</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td>Mark</td>
			<td>Otto</td>
			<td>@mdo</td>
			<td>Otto</td>
			<td>@mdo</td>
		</tr>
		<tr>
			<td>2</td>
			<td>Jacob</td>
			<td>Thornton</td>
			<td>@fat</td>
			<td>Otto</td>
			<td>@mdo</td>
		</tr>
		<tr>
			<td>3</td>
			<td colspan="2">Larry the Bird</td>
			<td>@twitter</td>
			<td>@twitter</td>
			<td>@twitter</td>
		</tr>
	</tbody>
</table>
<button type="button" class="btn btn-primary" id="add" >新增</button>
<button type="button" class="btn btn-primary" id="edit">编辑</button>
<button type="button" class="btn btn-primary" id="del">删除</button>
<script>
$(function($){
	$(":button").each(function(i){
	    var id = $(this).attr("id");
	    switch (id){
        	case 'add':
            	$(this).click(function(){
            	    location.href = "/admin/Admin/add";
                	});
        		break;
        	case 'edit':
        		$(this).click(function(){
            	    location.href = "/admin/Admin/edit";
                	});
        		break;
        	case 'del':
        		$(this).click(function(){
            	    location.href = "/admin/Admin/edit";
                	});
        		break;
        		default:
            		break;
	    };
	}
	);
});
</script>