<?php if($this->container):?>
<ul class="nav" role="navigation">
    <?php foreach ($this->container as $page) :?>
    <li class="dropdown">
      <a id="drop1" data-target="#"  href="#" role="button" class="dropdown-toggle" data-toggle="dropdown"><?php echo $page->label?> <b class="caret"></b></a>
      <?php if($page->pages):?>
      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
      <?php foreach ($page->pages as $child_page):?>
        <li role="presentation"><a role="menuitem" tabindex="-1" data-target="#"  href="<?php echo $child_page->getHref();?>"><?php echo $child_page->label?></a></li>
      <?php endforeach;?>
      </ul>
      <?php endif;?>
    </li>
    <?php endforeach;?>
</ul>
<?php endif;?>